AWSTemplateFormatVersion: 2010-09-09
Description: |
  This EC2 works on apache server
Resources:
  myec2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups:
        - launch-wizard-1
      Tags:
        - Key: Name
          Value : linux
  
